#!/bin/bash 
# judge this week is single week or not 
nums=$(expr $(date +%j) - 47)
if [[ $(expr $(expr $(expr $nums / 7) + 1) % 2) -eq 1 ]];then
	echo "| Time | Mon                    | Tue                   | Wed                  | Thu | Fri                |"
	echo "|------|------------------------|-----------------------|----------------------|-----|--------------------|"
	echo "| 1-2  | --                     | --                    | Compile Principle    | --  | Compile Principle  |"
	echo "| 3-4  | --                     | Network Project       | professional English | --  | Network Project    |"
	echo "| 5-6  | Embedded System Design | --                    | --                   | --  | Vocational Counsel |"
	echo "| 7-8  | Network Programming    | Information Retrieval | Security Programming | --  | --                 |"
	echo "| 9-10 | Mao                    | --                    | Mao                  | --  | --                 |"
else
	echo "| Time | Mon                    | Tue                   | Wed                  | Thu | Fri                |"
	echo "|------|------------------------|-----------------------|----------------------|-----|--------------------|"
	echo "| 1-2  | --                     | --                    | --                   | --  | Compile Principle  |"
	echo "| 3-4  | --                     | Network Project       | professional English | --  | --                 |"
	echo "| 5-6  | Embedded System Design | --                    | --                   | --  | Vocational Counsel |"
	echo "| 7-8  | Network Programming    | Information Retrieval | Security Programming | --  | --                 |"
	echo "| 9-10 | Mao                    | --                    | Mao                  | --  | --                 |"
fi






